### ISSUE TITLE
Place start script into VM folder next to .vbox and .vdi files

### ISSUE THREAD

**Issue by lexsulzer** [LinuxCompetenceCenter/TFTP#1]
Current start script at https://github.com/lccmediawiki/lccmediawikitoolsinapp/blob/master/lccmediawikiapp_start

**Comment by lexsulzer** [comment]
Obsolete.

**Comment by timoldenb** [comment]
Bitte aus dem Verteiler entfernen!

Am 06.11.2015 um 18:03 schrieb Lex Sulzer:

**Comment by lexsulzer** [comment]
Ich glaube das musst Du über Dein https://github.com/watching abstellen. Ich habe Dich aus allen Gruppen entfernt.
